### ISSUE TITLE
Error in broker while running async-message-patterns sample in EI 7

### ISSUE THREAD

**Issue by Manuri** [wso2/message-broker#101]
**Description:**
Following exception occurs when trying out the Topic scenario in async-message-patterns sample in EI7.

`
[2017-12-22 00:11:27,025] WARN {org.wso2.broker.amqp.AmqpConsumer$ErrorLogger} -  Error while sending message for tmp_127_0_0_1_10430_1
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at org.wso2.broker.amqp.codec.frames.HeaderFrame.writePayload(HeaderFrame.java:161)
	at org.wso2.broker.amqp.codec.frames.GeneralFrame.write(GeneralFrame.java:64)
	at org.wso2.broker.amqp.codec.AmqpEncoder.encode(AmqpEncoder.java:36)
	at org.wso2.broker.amqp.codec.AmqpEncoder.encode(AmqpEncoder.java:32)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	... 11 more
[2017-12-22 00:11:27,033] WARN {org.wso2.broker.amqp.AmqpConsumer$ErrorLogger} -  Error while sending message for tmp_127_0_0_1_10430_1
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at org.wso2.broker.amqp.codec.frames.ContentFrame.writePayload(ContentFrame.java:62)
	at org.wso2.broker.amqp.codec.frames.GeneralFrame.write(GeneralFrame.java:64)
	at org.wso2.broker.amqp.codec.AmqpEncoder.encode(AmqpEncoder.java:36)
	at org.wso2.broker.amqp.codec.AmqpEncoder.encode(AmqpEncoder.java:32)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	... 11 more
`

Tried the same with MB 3.1.0 and there was no such issue.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Broker 1.0.31 

**Steps to reproduce:**
Follow steps in Topics usage scenario of [1].

**Related Issues:**
https://github.com/wso2/product-ei/issues/1592 depends on this

[1] https://github.com/wso2/product-ei/blob/7.0.x/samples/async-messaging-patterns/README.md

**Comment by a5anka** [comment]
The issue was not observed in the latest release (https://github.com/wso2/message-broker/releases/tag/v1.0.46)
