### ISSUE TITLE
Exception while handling request

### ISSUE THREAD

**Issue by madhawa-gunasekara** [wso2/message-broker#110]
This is easily reproducible with durable subscription test case.

**Affected Product Version: product-ei:7.0.0-m6

**OS, DB, other environment details and versions: ubuntu 14, java version "1.8.0_144"

**Steps to reproduce:**
1. Start message broker by running the following command,
bin$ ./broker.sh

2. Ensure to have the common.balx running, if it's not running execute the following
bin$ ./integrator.sh ../samples/async-messaging-patterns/common.balx

3. Deploy the service by running the following command,
bin$ ./integrator.sh ../samples/async-messaging-patterns/durable.balx

[2018-01-03 15:06:56,935] WARN {org.wso2.broker.amqp.codec.handlers.AmqpDecoder} -  Exception while handling request
io.netty.handler.codec.DecoderException: org.wso2.broker.amqp.codec.AmqFrameDecodingException: Method 22 unknown in AMQP version 0-91 (while trying to decode class 40 method 22.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.broker.amqp.codec.AmqFrameDecodingException: Method 22 unknown in AMQP version 0-91 (while trying to decode class 40 method 22.
	at org.wso2.broker.amqp.codec.frames.AmqMethodRegistry.getFactory(AmqMethodRegistry.java:77)
	at org.wso2.broker.amqp.codec.handlers.AmqpDecoder.parseFrame(AmqpDecoder.java:134)
	at org.wso2.broker.amqp.codec.handlers.AmqpDecoder.decode(AmqpDecoder.java:77)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 16 more

**Comment by a5anka** [comment]
@madhawa-gunasekara @abeykoon 
It seems the andes-client is sending a frame (exchange.bound) that is undefined in AMQP 0-9-1 spec. Can we fix it in andes client?

![amap-spec](https://user-images.githubusercontent.com/1148405/34595404-b37b5c78-f1fd-11e7-92c3-f3d4717c8daf.png)

[1] http://www.amqp.org/specification/0-9-1/amqp-org-download
